- hosts: all
  become: yes
  become_user: root

  roles:
    - pypack

- hosts: master_group:slaver_group
  become: yes
  become_user: root

  roles:
    - docker

- hosts: master_group
  become: yes
  become_user: root

  roles:
    - master_couchdb


- hosts: slaver_group
  become: yes
  become_user: root

  roles:
    - slaver_couchdb

- hosts: normal_group
  become: yes
  become_user: root

  roles:
    - server