- hosts: all
  become: yes
  become_user: root

  roles:
    - docker
    - pypack
    - nodejs

- hosts: master_group
  become: yes
  become_user: root

  roles:
    - master_couchdb


- hosts: slaver_group
  become: yes
  become_user: root

  roles:
    - slaver_couchdb