- hosts: all
  become: yes
  become_user: root

  roles:
    - docker

- hosts: master_group
  become: yes
  become_user: root

  roles:
    - master_yml


- hosts: slaver_group
  become: yes
  become_user: root

  roles:
    - slaver_yml