---
- name: Transfer proxy file
  copy:
    src: 'test.py'
    dest: ~/
    owner: root
    mode: 0700

- name: Do shell
  become: yes
  become_method: sudo
  become_user: root
  shell: python ~/test.py /etc/environment

- name: Delete shell
  file:
    path: "~/test.py"
    state: absent