---
- name: Create docker-proxy directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Transfer proxy file
  copy:
    src: 'test1.py'
    dest: ~/
    owner: root
    mode:  0700

- name: Do shell
  become: yes
  become_method: sudo
  become_user: root
  shell: |
    python ~/test1.py /etc/systemd/system/docker.service.d/http-proxy.conf /etc/systemd/system/docker.service.d/https-proxy.conf
    systemctl daemon-reload
    systemctl restart docker

- name: Delete shell
  file:
    path: "~/test1.py"
    state: absent