---
- name: Synchronize dataset
  synchronize:
    src: syn_directory/dataset
    dest: /home/ubuntu/

- name: Synchronize model
  synchronize:
    src: syn_directory/keras_model
    dest: /home/ubuntu/

- name: Transfer sourcecode
  template:
    src: twitter_crawling.py.j2
    dest: /home/ubuntu/twitter_crawling.py

- name: Transfer utility file
  template:
    src: util.py.j2
    dest: /home/ubuntu/util.py

- name: Transfer script
  template:
    src: run.sh.j2
    dest: /home/ubuntu/run.sh

- name: Install Batchjobs on crontab
  become: yes
  become_method: sudo
  become_user: root
  cron:
    name: "Crawling"
    minute: "0"
    hour: "0"
    job: "home/ubuntu/run.sh >> home/ubuntu/testout"
    disabled: "no"
  tags:
   - cronjobs