---
- name: Transfer dbhost file
  template:
    src: dbhost.txt.j2
    dest: dbhost.txt

- name: Synchronization of src on the control machine to dest on the remote hosts
  synchronize:
    src: test
    dest: /home/ubuntu/