- name: Transfer script1
  template:
    src: runs.sh.j2
    dest: runs.sh

- name: Transfer script2
  template:
    src: runc.sh.j2
    dest: runc.sh

- name: Running back end application
  shell:
    sh runs.sh


- name: Running front end application
  shell:
    sh runc.sh